name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flask_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      BLOG_DB_HOST: "localhost"
      BLOG_DB_USER: "root"
      BLOG_DB_PASSWORD: "root"
      BLOG_DB_NAME: "flask_db"
      BLOG_DB_CURSOR: "DictCursor"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      DB_USER: "root"
      DB_PASS: "root"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: bash scripts/install_dependencies.sh
    - name: Wait for MySQL
      run: bash scripts/wait_for_mysql.sh
    - name: Generate credentials
      run: python scripts/generate_credentials.py --output ${{ runner.temp }}/credentials.json
    - name: Prepare DB schema
      run: bash scripts/prepare_db_schema.sh
    - name: Run smoke tests
      run: bash scripts/run_smoke_tests.sh
    - name: Clean credentials
      if: always()
      run: |
        python scripts/generate_credentials.py --clean --output src/credentials.json
        python scripts/generate_credentials.py --example --output src/credentials.json.example
